server:
  port: 8081
  address: 0.0.0.0

spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topics:
    manager-email: manager-emails
    candidate-email: candidate-emails