spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: /src/java/org/example/resources/config
server:
  port: 8888